### PR TITLE
[WIP] Implement automatic file type detection for the --image switch

### PR DESCRIPTION
**Pull request by Kriegslustig**
Graphviz supports more than just PNG. This feature checks the --image parameter's file extension and passes that as a file type to Graphviz instead.

So this:

```bash
madge --image ./dependency-graph.svg src/*
```

Now creates an SVG file of the graph (which is better suited IMHO).

If you think this is a change you'd like to merge I'll document it and push it to this PR. If you'd like it to be a separate switch, I'll gladly implement it that way.

This PR also fixes a small bug with [graphviz error handling](https://github.com/pahen/madge/commit/5199e11ae8751de86ad6466660a171fd6d156615).

P.S.: If you need any help with the v1 release, I'd love to help. So just say the word. I could help you implementing the pending tests for example. :)

### CODE REVIEW

**Comment by pahen** [comment]
Awesome! SVG is definitely better! I like how you implemented it. I'll take a closer look when I'm back from my vacation next week :)

**Comment by pahen** [comment]
Thanks for your effort! I've implemented it in https://github.com/pahen/madge/commit/a757c57b7dab9262b4f9189b82cbfd0e45822979 with some modifications due to new changes in the API.

**Comment by Kriegslustig** [comment]
Alright, thanks. Just tell me if you need any help. :)

**Comment by pahen** [comment]
Sure! I would love some help :) I'm ready for some feedback on the 1.0 release soon. Maybe you are up for some review/testing when I've created the 1.0 PR?

**Comment by Kriegslustig** [comment]
Sure thing! I'll watch the repo so I'll get a notification.

**Pull request closed without merging**
