### PR TITLE
Migrate to ESM

### PR DESCRIPTION
**Pull request by fdc-viktor-luft**
- [ ] Verify that the generated output is still fine
- [ ] Check that inclusion of package still works when installed
- [ ] Fix broken test "supports resolve root paths in webpack config"

### CODE REVIEW

**Comment by fdc-viktor-luft** [comment]
@pahen This change was necessary in order to update some of the very outdated dependencies. Non-ESM projects will not be able to import "madge" anymore via "require". Hopefully, that is not a blocker, as CJS should be already abandoned by a large majority, especially as even more popular libs such as "chalk" have gone this path a long time ago.

What do you think?

And, do you have maybe an idea why the one remaining test might fail?

**Comment by fdc-viktor-luft** [comment]
@pahen Any feedback from your site? Before investing more time into the PR, I wanted to make sure you agree with this step.

**Comment by pahen** [comment]
> @pahen Any feedback from your site? Before investing more time into the PR, I wanted to make sure you agree with this step.

Note sure about this. The fact that non-ESM projects can't use madge is a big blocker to me.

**Comment by vikingair** [comment]
@pahen You are the decision maker. In that case, we will need to keep the long time outdated "chalk" dependency or replace it by e.g. [picocolors](https://www.npmjs.com/package/picocolors).

What would you prefer?

**Comment by pahen** [comment]
> @pahen You are the decision maker. In that case, we will need to keep the long time outdated "chalk" dependency or replace it by e.g. [picocolors](https://www.npmjs.com/package/picocolors).
> 
> What would you prefer?

Replacing `chalk` with `picocolors` sounds good to me if it provides the same functionally that madge uses.

**Comment by vikingair** [comment]
Will see when I can find the time :P

**Pull request closed without merging**
