### PR TITLE
Correct engine requirements

### PR DESCRIPTION
**Pull request by fdc-viktor-luft**
Is the `travis.yml` still used or can it be completely removed?

### CODE REVIEW

**Comment by kamiazya** [comment]
@fdc-viktor-luft Hi,

If the updated engine requirement is accurate, please consider updating madge to use version 2 of the ts-graphviz package, which I maintain.

Version 2 of ts-graphviz supports Node.js 18 and above. I had not submitted a patch earlier because I believed madge was still supporting Node.js 14.

Since version 1 of ts-graphviz will no longer receive patches, I recommend switching to version 2 at this time.

**Comment by kamiazya** [comment]
I tested it locally, and it seems that only the change to package.json is needed since there are no API changes!

```bash
$ node -v
v18.20.3

# fix package.json
#   
# “ts-graphviz”:“^2.1.2”.

$ npm i
...

$ node bin/cli.js -i /dev/null bin/cli.js 
Processed 8 files (878ms) (1 warning)

✔ Image created at /dev/null
```

**Comment by fdc-viktor-luft** [comment]
I'll include the update. Thanks for pointing this out. Since an update to the dependency dependency-tree was already merged that has this requirement, adjusting the engine requirement was kind of just missing.

I planned several other dependency updates as well.

But first I'd like to merge this one: https://github.com/pahen/madge/pull/418
This includes a cleanup of all deps.

Then I'll do the recommended update of ts-graphviz. Thanks for your testing and the hint.

**Comment by PabloLION** [comment]
### PR description
I'm just back to open-source world. I see that the description is not very clear, here's the change I suggest

```text
Update Node.js version requirements and testing configurations.

- Increase the minimum required Node.js version from ">=14" to ">=18" in `package.json` to ensure compatibility with newer features and security updates.
- Update the Node.js version in `.nvmrc` from "18" to "20", aligning the development environment with the latest stable release.
- Adjust `.travis.yml` to test against Node.js versions "18" and "20", removing version "14" from the testing matrix to reflect the updated version requirements and focus on current and future Node.js versions.
```

### Another thing

> I recommend switching to version 2 at this time.

Maybe we can do it in another PR?

### Off-topic
Today I tried the [Copilot Workspace session](https://copilot-workspace.githubnext.com/pahen/madge/pull/419?shareId=ef3a4cd7-f826-4aa3-9425-17035af0529b). I assume this tool can help relief the workload. You guys can try it too.

**Review by pahen — APPROVED** [review]

**Comment by pahen** [comment]
> Is the `travis.yml` still used or can it be completely removed?

It can be removed. But should maybe be done in another PR since everything related to Travis should be removed, including the build status badge in the README.

**Pull request merged**
