### PR TITLE
Move typescript to peer dependencies

### PR DESCRIPTION
**Pull request by kamiazya**
## What was the problem

Currently, the typescript package is used to load tsconfig and is not used by users who only use JavaScript.

The implementation is such that `require('typescript')` is actually done in the function, so it does not affect all users.

However, including it in the dependencies may restrict the version of TypeScript that can be used, and a warning may be displayed if a user specifies a different version when installing madge.

## Solution

Move the `typescript` dependency to the "peerDependencies" field and make the version specification a wildcard.

Also add the "peerDependenciesMeta" field and make typescript as optional. 

This is to avoid conflicts with the user's specification, and also because of the version specification in the directive `detective-typescript`, we expect to use the `typescript` version specified by the `detective-typescript` package, or the `typescript` version specified by the user, to be used when resolving the version. or the user-specified `typescript` version is expected to be used.

"peerDependencies" that specify only `typescript: *` can be ignored during development, so we specify typescript@^4.5.5, which is the same as the `detective-typescript@9.0.0` package.

### CODE REVIEW

**Comment by kamiazya** [comment]
Since it might be better to use `peerDependencies` and `peerDependenciesMeta`, we have returned PR to Draft for a while longer to consider how to handle this.

https://classic.yarnpkg.com/en/docs/package-json/#toc-peerdependencies

**Comment by PabloLION** [comment]
From what I read in [NPM Docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json), I'd say an optional peer dependency suits better here.

**Comment by kamiazya** [comment]
The revised policy has been changed, as it seems more appropriate to specify in peerDepenedencies.

**Review by PabloLION — APPROVED** [review]
LGTM

**Comment by kamiazya** [comment]
Previous studies: https://github.com/pahen/madge/pull/275

**Pull request merged**
