### PR TITLE
Show skipped files as warnings (disable with —-no-warning)

### LINKED ISSUE #107: Handle paths that cannot be resolved
Sometimes dependency-tree cannot resolve all the required paths (due to bugs or configuration problems). Madge should not let these errors go unnoticed since it can result in an incorrect dependency graph. See dependents/node-dependency-tree#53 for a discussion of this.

### PR DESCRIPTION
**Pull request by pahen**
Fixes #107

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Nice job with the thoroughness of the solution.

**Comment by pahen** [comment]
Thanks! But now I'm starting to think it's maybe better to have warnings disabled by default? Most of the time you don't want to see them.

**Comment by pahen** [comment]
I decided to change to `--show-skipped` instead in v1.4.1.

**Comment by mrjoelkemp** [comment]
Yeah, having to opt-out of warnings felt like a breaking change. Opting-in is definitely better.

**Comment by pahen** [comment]
Yes, I agree! Renamed `--show-skipped` to `--warning` now in v1.4.2. Having fever today so is a little bit confused :)

**Comment by mrjoelkemp** [comment]
Feel better ❤️

**Comment by pahen** [comment]
Thanks Joel!

**Pull request merged**
